POST http://127.0.0.1:5000/api/v1/customers/8c168e91-6b60-45d6-b591-46cb145999f7/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhjMTY4ZTkxLTZiNjAtNDVkNi1iNTkxLTQ2Y2IxNDU5OTlmNyIsImV4cCI6MTczNjI0NDc2OX0.ELzrcGk5ttXUFcwqRqyFnQCNOV5lFPlwVhLzo-bGEhw

{
    "customer_id": "8c168e91-6b60-45d6-b591-46cb145999f7",
    "shipping_address": "test",
    "order_address": "test",
    "order_email": "test@test.com"
}